### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lucasb-eyer** [allenai/aokvqa#10]
Hi, it does not seem like you gave the dataset (label files) any license. For OKVQA you did so in the json file itself (CC-BY-4.0), but for A-OKVQA I cannot find anything. Could you please explicitly set a license for the dataset, maybe on the homepage next to the downloads?
![image](https://github.com/allenai/aokvqa/assets/1476029/bf550d60-6edb-4aec-961a-13546553d629)
Cheers!

**Comment by apoorvkh** [comment]
Hey Lucas,

Thanks for bringing this up. As you've suggested, we've added a license to the website. Our dataset (not the COCO images) is licensed under CC-BY-4.0.

![image](https://github.com/allenai/aokvqa/assets/7005565/3a673604-5807-4c17-9c21-e2c32cf242e0)

Hope that looks good now!
