### ISSUE TITLE
1,000 question labeled what kind of knowledge type are released?

### ISSUE THREAD

**Issue by simba0626** [allenai/aokvqa#11]
Dear Authors,

"To analyze the knowledge required in A-OKVQA more quantitatively, the authors annotated a randomly sampled subset of 1,000 questions in the A-OKVQA test. To label what kind of knowledge type was required to answer the questions."
It is great work.
Would you like to release the annotations ?

Thank you

ywsun

**Comment by apoorvkh** [comment]
Yes, we are able to release the annotations. You can find them here:
[kt_annotation_res - kt_annotation_res-2.csv](https://github.com/allenai/aokvqa/files/14335147/kt_annotation_res.-.kt_annotation_res-2.csv)

Hope that helps!
