### ISSUE TITLE
The prediction output file does not match the required format

### ISSUE THREAD

**Issue by Taoismer** [allenai/aokvqa#12]
I used the code in the repo to genereate prediction_val.json for evaluation, but the generated format does not match the required format:

{
    '<question_id>' : {
        'multiple_choice' : '<prediction>',
        'direct_answer' : '<prediction>'
    }
}

Is it a bug?

**Comment by apoorvkh** [comment]
You will need to provide more details before I am able to help you.

Specifically, which commands did you run? And what does your output look like, if not in the format above?

**Comment by apoorvkh** [comment]
Closing this issue for now, but please re-open if you are able to provide more details.
