### ISSUE TITLE
Annotation file is absent

### ISSUE THREAD

**Issue by Taoismer** [allenai/aokvqa#13]
It seems there should be a aokvqa_v1p0_test_w_ans.json in the https://prior-datasets.s3.us-east-2.amazonaws.com/aokvqa/aokvqa_v1p0.tar.gz, while it is absence

**Comment by Taoismer** [comment]
There is no correct answer in test annotation file

**Comment by apoorvkh** [comment]
Hey @Taoismer, the test set annotations are a secret (otherwise people may train on test) and we intentionally don’t provide them.

You can get test metrics by submitting your test predictions to

https://leaderboard.allenai.org/a-okvqa
