### ISSUE TITLE
The meaning of "difficult_direct_answer"

### ISSUE THREAD

**Issue by duzx16** [allenai/aokvqa#2]
Hi. I am wondering what the meaning of `difficult_direct_answer` in the json file is. I found that the evaluation code skipped examples whose `difficult_direct_answer` is False for the multiple choice setting, but it was never mentioned in the paper.

**Comment by apoorvkh** [comment]
`difficult_direct_answer` means that there could be many ways to answer a question when not given choices (e.g. we can see significant diversity in the list of `direct_answers` already gathered). And so, it might not be correct to compute direct answer accuracy with our metric on these questions. Instead, we exclude them from evaluation in the direct answer setting.

**Comment by duzx16** [comment]
Well, in line 14-15 of `eval_predictions.py`, the examples with `difficult_direct_answer` being `True` are excluded in the multiple choice setting instead of the direct answer setting, it that correct?
```
if multiple_choice:
    dataset = {k:v for k,v in dataset.items() if v['difficult_direct_answer'] is False}
```

**Comment by duzx16** [comment]
> `difficult_direct_answer` means that there could be many ways to answer a question when not given choices (e.g. we can see significant diversity in the list of `direct_answers` already gathered). And so, it might not be correct to compute direct answer accuracy with our metric on these questions. Instead, we exclude them from evaluation in the direct answer setting.

@apoorvkh Well, in line 14-15 of `eval_predictions.py`, the examples with `difficult_direct_answer` being `True` are excluded in the multiple choice setting instead of the direct answer setting, it that correct?
```
if multiple_choice:
    dataset = {k:v for k,v in dataset.items() if v['difficult_direct_answer'] is False}
```

**Comment by apoorvkh** [comment]
Ah, looks like this file was out of date. Thanks for catching that, I’ve corrected it now.
