### ISSUE TITLE
Can you provide the generated rationales results from your trained ClipCap on test set?

### ISSUE THREAD

**Issue by ParadoxZW** [allenai/aokvqa#4]
Hi, thanks to your great work!
Can you provide the generated rationales results from your trained ClipCap on test set, which you used in the experiments `ClipCap → Ratl. → GPT` in the paper?

**Comment by apoorvkh** [comment]
Hey, thanks! This should not be difficult to reproduce, as we've provided our trained ClipCap weights [here](https://github.com/allenai/aokvqa/tree/main#models-and-predictions) and instructions for generating rationales with this model [here](https://github.com/allenai/aokvqa/blob/ClipCap/README.md#generating-captions--rationales). You can run this on a single consumer-grade GPU.
