### ISSUE TITLE
Leaderboard is a little messy

### ISSUE THREAD

**Issue by codezakh** [allenai/aokvqa#5]
**Context**: We are working on VQA and using A-OKVQA as one of our primary datasets. We will eventually be submitting to the leaderboard.

It currently looks like this:
![image](https://user-images.githubusercontent.com/4918041/195216361-a883360b-7763-46fa-8804-a129d3b10cdd.png)
Many of the top scoring published submissions are anonymous or provide no details about their approach. This is against the stated guidelines:
> Share how you solved it: you must share information about how the task was solved. For example, you can link to a code repository, an academic paper or a blog post.
Share who you are: you must identify yourself, so others can ask you about your approach. Anonymous submissions are not allowed.

I don't know if there's a solution for this (the abductive NLI leaderboard is also like this, but more details for the top submissions) and manually vetting the leaderboard would definitely take too much time. Is there a way to have a distinction between "verified" and "unverified" submissions, with the verified submissions linked to a paper, github repo, or blog post with a contact email?

**Comment by apoorvkh** [comment]
Thanks for your note -- we will consider taking a pass over the leaderboard in the near future. And, yes, it's pretty hard to manually vet submissions. Those are good ideas, but we're not really responsible for leaderboard features. Consider contacting [leaderboard@allenai.org](mailto:leaderboard@allenai.org) instead!

**Comment by codezakh** [comment]
Gotcha, thanks for the reply -- it sounds like (a) this isn't a real problem (b) it'll probably fix itself over time as people make submissions and take credit for them. 

Thanks for the great dataset! I'm closing this issue.
