### ISSUE TITLE
Where to download images from Coco website?

### ISSUE THREAD

**Issue by george-adams1** [allenai/aokvqa#8]
The allen.ai website says that the images can be downloaded from the COCO dataset website: 
![image](https://github.com/allenai/aokvqa/assets/51809360/f5b901df-4061-4140-ab82-c941855c99d3)

But on the COCO website's download page, I am unsure which to install as none explicitly state A-OKVQA. The link to the page: https://cocodataset.org/#download

**Comment by apoorvkh** [comment]
We use the COCO 2017 split. In the [Getting Started](https://github.com/allenai/aokvqa#getting-started) section of this repo's readme, I've included specific instructions for how to download the COCO data.

```bash
export COCO_DIR=./datasets/coco/
mkdir -p ${COCO_DIR}

for split in train val test; do
    wget "http://images.cocodataset.org/zips/${split}2017.zip"
    unzip "${split}2017.zip" -d ${COCO_DIR}; rm "${split}2017.zip"
done

wget http://images.cocodataset.org/annotations/annotations_trainval2017.zip
unzip annotations_trainval2017.zip -d ${COCO_DIR}; rm annotations_trainval2017.zip
```
