### ISSUE TITLE
how to calculate mean Q distance?

### ISSUE THREAD

**Issue by jorie-peng** [allenai/aokvqa#9]
A-OKVQA is a really great dataset! In paper, we can see many analysis about it. I have a question about Table 2. 
From the paper ,it uses cosine distances in a sentence transformer space, but how to understand **pairwise**, for 17K questions, we should calculate 17K * 17K times? 
It would be better if the code could be provided.
![image](https://github.com/allenai/aokvqa/assets/54258789/7cad0677-3617-412e-83fd-34980ce24f70)

**Comment by jorie-peng** [comment]
Here is my code, but the distance is only 0.34.
```
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim
model = SentenceTransformer('sentence-transformers/average_word_embeddings_glove.6B.300d')
f = 'xx/aokvqa_train_cocoformat.json'
jsfile = json.load(open(f,'r'))
question_aokvqa = []
question_emb = []
for ann in jsfile:
    q = ann['question'].lower()
    question_aokvqa.append(q)
tensors = model.encode(question_aokvqa, convert_to_tensor=True)
sims2 = cos_sim(tensors, tensors)
print(torch.mean(sims2))
```

**Comment by apoorvkh** [comment]
Thank you!

We didn't use `sentence-transformers/average_word_embeddings_glove.6B.300d` for this measurement (that's not actually a sentence transformer anyway).

If you refer to our text, you can see that we used [`sentence-transformers/multi-qa-MiniLM-L6-cos-v1`](https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1).

![image](https://github.com/allenai/aokvqa/assets/7005565/f5b255f4-0dac-4f76-bfcc-8912417382dd)
![image](https://github.com/allenai/aokvqa/assets/7005565/b128df41-d690-4820-8442-502e71b62505)

Also, notice that you are currently computing cosing *similarity*, not distance: `sims2 = cos_sim(tensors, tensors)`

Please try again and re-open this issue if you still encounter issues!
